databases:
  - name: mare-alta-db
    databaseName: mare_alta
    user: mare_alta_user
    plan: free # Ajuste para starter/standard se necessário, free expira em 30 dias em alguns casos ou é limitado

services:
  - type: web
    name: mare-alta
    env: docker
    region: oregon
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: mare-alta-db
          property: connectionString
    autoDeploy: true
